# Generated by Django 5.1.5 on 2025-02-06 08:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The official name of the institution.', max_length=255)),
                ('type', models.CharField(choices=[('Centrul de Excelenţă', 'Centrul de Excelenţă'), ('Colegiul', 'Colegiul'), ('Școala Profesională', 'Școala Profesională')], help_text='The type of the institution.', max_length=255)),
                ('founding_authority', models.CharField(blank=True, default='', help_text='The authority or organization that founded the institution.', max_length=255)),
                ('physical_address', models.CharField(help_text='The physical address of the institution, including street, city, and postal code.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='The official contact email address of the institution.', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='The official website URL of the institution.', null=True)),
                ('phone', models.CharField(help_text='The contact phone number of the institution.', max_length=255, validators=[django.core.validators.RegexValidator('^([\\d\\s\\W]+)(,\\s[\\d\\s\\W]+)*$')])),
                ('summary', models.TextField(help_text="A brief summary of the institution's key details.")),
                ('description', models.TextField(blank=True, default='', help_text='Optional rich text providing detailed information about the institution, such as specialties and study duration.')),
                ('longitude', models.DecimalField(blank=True, decimal_places=10, help_text="The longitude coordinate of the institution's location.", max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))])),
                ('latitude', models.DecimalField(blank=True, decimal_places=10, help_text="The latitude coordinate of the institution's location.", max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))])),
                ('created_by', models.ForeignKey(blank=True, help_text='The user who created the institution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='The user who updated the institution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'physical_address'), name='unique_institution_address')],
            },
        ),
    ]
