# Generated by Django 5.1.5 on 2025-01-17 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='The official name of the institution.', max_length=255)),
                ('fields_of_professional_training', models.JSONField(default=dict, help_text='A JSON object listing the fields of professional training offered by the institution.')),
                ('founding_authority', models.CharField(help_text='The authority or organization that founded the institution.', max_length=255)),
                ('specialization', models.CharField(help_text='The main area of specialization or focus of the institution.', max_length=255)),
                ('physical_address', models.CharField(help_text='The physical address of the institution, including street, city, and postal code.', max_length=255)),
                ('email', models.EmailField(blank=True, help_text='The official contact email address of the institution.', max_length=255, null=True)),
                ('website', models.URLField(blank=True, help_text='The official website URL of the institution.', null=True)),
                ('phone', models.CharField(blank=True, help_text='The contact phone number of the institution.', max_length=255, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text="The longitude coordinate of the institution's location.", max_digits=9, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text="The latitude coordinate of the institution's location.", max_digits=9, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'physical_address'), name='unique_institution_address')],
            },
        ),
    ]
