# Generated by Django 5.1.5 on 2025-03-25 11:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creat'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user who created the institution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creat de'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Optional rich text providing detailed information about the institution, such as specialties and study duration.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='email',
            field=models.EmailField(blank=True, help_text='The official contact email address of the institution.', max_length=255, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='founding_authority',
            field=models.CharField(blank=True, default='', help_text='The authority or organization that founded the institution.', max_length=255, verbose_name='Fondator'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text="The latitude coordinate of the institution's location.", max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-90')), django.core.validators.MaxValueValidator(Decimal('90'))], verbose_name='Latitudine'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, help_text="The longitude coordinate of the institution's location.", max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('-180')), django.core.validators.MaxValueValidator(Decimal('180'))], verbose_name='Longitudine'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(help_text='The official name of the institution.', max_length=255, verbose_name='Instituția de învățământ profesional tehnic'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='phone',
            field=models.CharField(help_text='The contact phone number of the institution.', max_length=255, validators=[django.core.validators.RegexValidator('^([\\d\\s\\W]+)(,\\s[\\d\\s\\W]+)*$')], verbose_name='Telefon director / anticameră'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='physical_address',
            field=models.CharField(help_text='The physical address of the institution, including street, city, and postal code.', max_length=255, verbose_name='Adresa juridică, inclusiv pentru sediile arondate'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='summary',
            field=models.TextField(help_text="A brief summary of the institution's key details.", verbose_name='Inst summary'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.CharField(choices=[('Centrul de Excelenţă', 'Centrul de Excelenţă'), ('Colegiul', 'Colegiul'), ('Școala Profesională', 'Școala Profesională')], help_text='The type of the institution.', max_length=255, verbose_name='Tipul institutiei'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizat'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='The user who updated the institution.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institutions_updated', to=settings.AUTH_USER_MODEL, verbose_name='Actualizat de'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='website',
            field=models.URLField(blank=True, help_text='The official website URL of the institution.', null=True, verbose_name='Pagina web'),
        ),
    ]
