services:
  vet-api:
    build: .
    image: vet-django
    ports:
      - "8000:8000"
      - "441:441"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=vet_postgres
    depends_on:
      - vet-postgres

  vet-postgres:
    hostname: vet_postgres
    image: postgres:17
    ports:
      - "5432:5432"
    volumes:
      - vet_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vet

  vet-nginx-manager:
    image: 'jc21/nginx-proxy-manager:2.11.3'
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  vet_postgres_data:
    name: vet_postgres_data