services:
  vet-api:
    build: .
    image: vet-django
    hostname: vet_django
    ports:
      - "8000:8000"
      - "441:441"
    env_file:
      - .env
    volumes:
      - vet_static_volume:/usr/app/static/
    environment:
      - POSTGRES_HOST=vet_postgres

  vet-postgres:
    hostname: vet_postgres
    image: postgres:17-bullseye
    ports:
      - "5432:5432"
    volumes:
      - vet_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=vet

  vet-nginx:
    image: nginx:1.27.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - vet_static_volume:/usr/app/static
      - ./static/map-widget.js:/usr/app/static/map-widget.js
    depends_on:
      - vet-api

volumes:
  vet_postgres_data:
    name: vet_postgres_data
  vet_static_volume:
    name: vet_static_volume